name: AngeloPL
version: ${project.version}
main: fr.agiusangelo.angeloPL.Main
api-version: '1.20'
authors: [ AGIUS Angelo ]
description: Le plugin pour le serveur Minecraft du Twitch de Angelo
website: https://github.com/Angelo-Agius
commands:
  easter:
    description: EsterEgg tkt frr
    usage: /<command> <joueur> <args>
    permission: easter.use
    permission-message: Vous n'avez pas la permission d'utiliser cette commande.
  openinv:
    description: Ouvre l'inventaire d'un joueur
    usage: /<command> <joueur>
    permission: openinv.use
    permission-message: Vous n'avez pas la permission d'utiliser cette commande.
permissions:
  easter.use:
    default: op
  openinv:
    default: op